using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Companion.Infrastructure.Migrations
{
    /// <summary>
    /// A3. Gives shadow comparisons an owner and an exact evidence identity, and purges the
    /// rows that can never have one.
    ///
    /// These rows quote verbatim user messages and, for renderer subjects, both replies. They
    /// had no UserId at all, so the only available forgetting was a case-insensitive
    /// substring search across every user of the instance: it deleted rows that merely shared
    /// a phrase, missed any paraphrase, and could reach another user's diagnostics.
    ///
    /// Legacy rows cannot be rescued. Attributing them to a turn would be inventing
    /// ownership, and the first /forget after that invention would delete on a guess. Shadow
    /// data is diagnostic rather than authoritative, so the trade is not close: the rows are
    /// purged. What is lost is evaluation telemetry that can be regenerated by observing
    /// again; what is avoided is verbatim conversation that could never be removed on request.
    ///
    /// The purge itself runs in the migration that follows, because it tests SourceMemoryId
    /// and that column does not exist until then.
    /// </summary>
    public partial class AddShadowComparisonOwnership : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "ConversationId",
                table: "ShadowComparisons",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SourceMessageId",
                table: "ShadowComparisons",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "UserId",
                table: "ShadowComparisons",
                type: "TEXT",
                nullable: true);

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ConversationId",
                table: "ShadowComparisons");

            migrationBuilder.DropColumn(
                name: "SourceMessageId",
                table: "ShadowComparisons");

            migrationBuilder.DropColumn(
                name: "UserId",
                table: "ShadowComparisons");
        }
    }
}
