// <auto-generated />
using System;
using Companion.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Companion.Infrastructure.Migrations
{
    [DbContext(typeof(CompanionDbContext))]
    [Migration("20260826125613_AddDerivedEvidenceLineage")]
    partial class AddDerivedEvidenceLineage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("Companion.Core.Domain.ActivityBranchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ActivatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivationEvidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerBindingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedKeysJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BranchPointQuestionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ContentWithheld")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentQuestionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinalGuess")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("FinalGuessCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HypothesesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentBranchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProcedureDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Retention")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("TerminalAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .IsUnique();

                    b.HasIndex("TerminalAt");

                    b.HasIndex("UserId", "ConversationId");

                    b.ToTable("ActivityBranches");
                });

            modelBuilder.Entity("Companion.Core.Domain.Anticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EncouragedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EventAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evidence")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FollowedUpAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Anticipations");
                });

            modelBuilder.Entity("Companion.Core.Domain.AttentionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastActivatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("Strength")
                        .HasColumnType("REAL");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status", "LastActivatedAt");

                    b.ToTable("AttentionItems");
                });

            modelBuilder.Entity("Companion.Core.Domain.CapabilityDescriptor", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputTypes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastVerifiedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LocalOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputTypes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Capabilities");
                });

            modelBuilder.Entity("Companion.Core.Domain.CompanionMoodTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AppliedValence")
                        .HasColumnType("REAL");

                    b.Property<long?>("CompactedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EvidenceForgotten")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NewSpirits")
                        .HasColumnType("REAL");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PreviousSpirits")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("SourceEvidenceEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Version")
                        .IsUnique();

                    b.ToTable("CompanionMoodTransitions");
                });

            modelBuilder.Entity("Companion.Core.Domain.CompanionPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Affinity")
                        .HasColumnType("REAL");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB");

                    b.Property<bool>("EvidenceForgotten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceMessageIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Observations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CompanionPreferences");
                });

            modelBuilder.Entity("Companion.Core.Domain.Concept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CanonicalName")
                        .IsUnique();

                    b.ToTable("Concepts");
                });

            modelBuilder.Entity("Companion.Core.Domain.ConceptAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Alias");

                    b.ToTable("ConceptAliases");
                });

            modelBuilder.Entity("Companion.Core.Domain.ConceptAssertion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB");

                    b.Property<long>("FirstObserved")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Importance")
                        .HasColumnType("REAL");

                    b.Property<long>("LastConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Relation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetConceptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Validity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ConceptId");

                    b.ToTable("ConceptAssertions");
                });

            modelBuilder.Entity("Companion.Core.Domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DoNotRemember")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastActivityAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Companion.Core.Domain.Curiosity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("About")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("GapId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReflectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("VoicedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReflectionId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Curiosities");
                });

            modelBuilder.Entity("Companion.Core.Domain.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DecidedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("Companion.Core.Domain.EmotionalSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvidenceEventId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EvidenceForgotten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FollowedUp")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ForgottenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sentiment")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Valence")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("EmotionalSignals");
                });

            modelBuilder.Entity("Companion.Core.Domain.EpisodicMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB");

                    b.Property<string>("EmotionalSignificance")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpisodeStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("EventTime")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Importance")
                        .HasColumnType("REAL");

                    b.Property<long>("MentionedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedProject")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimePrecision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("EpisodicMemories");
                });

            modelBuilder.Entity("Companion.Core.Domain.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EvidenceForgotten")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EvidenceMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "At");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Companion.Core.Domain.FeedbackRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Companion.Core.Domain.FrameBoundaryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeactivatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EvidenceMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("StatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ConversationId", "SceneRef", "Status");

                    b.ToTable("FrameBoundaries");
                });

            modelBuilder.Entity("Companion.Core.Domain.FrameSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveCompanionCharacterId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedKeysJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CharactersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Continuity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EnteredAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastTransitionAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NarratorCharacterId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NarratorKind")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Person")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransitionLogJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ViewpointCharacterId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("EndedAt");

                    b.HasIndex("UserId", "ConversationId", "Status");

                    b.ToTable("FrameSessions");
                });

            modelBuilder.Entity("Companion.Core.Domain.KnowledgeGap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CuriosityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceMessageIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Occurrences")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pursuit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceRef")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubjectConceptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("UserId", "Kind", "Subject");

                    b.ToTable("KnowledgeGaps");
                });

            modelBuilder.Entity("Companion.Core.Domain.MemoryAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssociationType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastReinforcedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceMemoryId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Strength")
                        .HasColumnType("REAL");

                    b.Property<Guid>("TargetMemoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SourceMemoryId");

                    b.HasIndex("UserId", "TargetMemoryId");

                    b.ToTable("MemoryAssociations");
                });

            modelBuilder.Entity("Companion.Core.Domain.MemoryEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemoryKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MemoryId");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("Companion.Core.Domain.MemoryRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("After")
                        .HasColumnType("TEXT");

                    b.Property<string>("Before")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemoryKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MemoryId");

                    b.ToTable("Revisions");
                });

            modelBuilder.Entity("Companion.Core.Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishReason")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GenerationRounds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReplyToId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Truncated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "Timestamp");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Companion.Core.Domain.ModelCallRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletionChars")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ok")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptChars")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("ModelCalls");
                });

            modelBuilder.Entity("Companion.Core.Domain.OpenLoop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClosedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClosureEvidence")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB");

                    b.Property<long?>("ExpectedFollowUp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("OpenLoops");
                });

            modelBuilder.Entity("Companion.Core.Domain.OutboundMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("SentAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SentAt");

                    b.ToTable("OutboundMessages");
                });

            modelBuilder.Entity("Companion.Core.Domain.PendingClarification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AmbiguityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OriginalMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ResolvedProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Status");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("PendingClarifications");
                });

            modelBuilder.Entity("Companion.Core.Domain.Procedure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("Companion.Core.Domain.ProcedureRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcedureId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceMessageId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcedureId");

                    b.HasIndex("UserId", "ProcedureId", "Timestamp");

                    b.ToTable("ProcedureRevisions");
                });

            modelBuilder.Entity("Companion.Core.Domain.ProcedureStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProcedureId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcedureId");

                    b.HasIndex("UserId", "ProcedureId", "Order");

                    b.ToTable("ProcedureSteps");
                });

            modelBuilder.Entity("Companion.Core.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB");

                    b.Property<long>("LastActivityAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Companion.Core.Domain.ProjectAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectAliases");
                });

            modelBuilder.Entity("Companion.Core.Domain.ProjectEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Timestamp");

                    b.ToTable("ProjectEvents");
                });

            modelBuilder.Entity("Companion.Core.Domain.Reflection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContinuesReflectionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CoveredThrough")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB");

                    b.Property<bool>("EvidenceForgotten")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessagesReflected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Musing")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMessageIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ThreadSettled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "ThreadId");

                    b.ToTable("Reflections");
                });

            modelBuilder.Entity("Companion.Core.Domain.SemanticMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB");

                    b.Property<long>("FirstObserved")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Importance")
                        .HasColumnType("REAL");

                    b.Property<long>("LastConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedFact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Predicate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedProject")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Validity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("SemanticMemories");
                });

            modelBuilder.Entity("Companion.Core.Domain.ShadowComparison", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Agreed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Applied")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Input")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Legacy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Subject", "Timestamp");

                    b.ToTable("ShadowComparisons");
                });

            modelBuilder.Entity("Companion.Core.Domain.SharedExperiencePerspective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExperienceId");

                    b.ToTable("SharedExperiencePerspectives");
                });

            modelBuilder.Entity("Companion.Core.Domain.ToolCallRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ok")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("ToolCalls");
                });

            modelBuilder.Entity("Companion.Core.Domain.TurnRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssistantPreview")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("BoundQuestion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Decisions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("FocalCovered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FocalTerms")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Intent")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<double>("IntentConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("IntentRunnerUp")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Move")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("PacketTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plan")
                        .HasMaxLength(2500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionConfidence")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetrievalQuery")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Retrieved")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPreview")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("TurnRecords");
                });

            modelBuilder.Entity("Companion.Core.Domain.UserPreferenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveSlot")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeactivatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvidenceEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EvidenceMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceStatement")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Restrictive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RevocationEvidenceMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevocationStatement")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("StatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ActiveSlot")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Companion.Core.Domain.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanionGender")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanionName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanionPronouns")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<double>("CompanionSpirits")
                        .HasColumnType("REAL");

                    b.Property<long?>("CompanionSpiritsNudgedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Persona")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalityPreset")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Companion.Core.Domain.Message", b =>
                {
                    b.HasOne("Companion.Core.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Companion.Core.Domain.ProcedureRevision", b =>
                {
                    b.HasOne("Companion.Core.Domain.Procedure", null)
                        .WithMany("Revisions")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Companion.Core.Domain.ProcedureStep", b =>
                {
                    b.HasOne("Companion.Core.Domain.Procedure", null)
                        .WithMany("Steps")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Companion.Core.Domain.Procedure", b =>
                {
                    b.Navigation("Revisions");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
