using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Companion.Infrastructure.Migrations
{
    /// <summary>
    /// A3, completing the ownership change. Adds the memory lineage a supersession-pair row
    /// needs -- those rows are about a stored MEMORY, not a message, so a message id would
    /// never find them; the id used to be smuggled through the excerpt list as a formatted
    /// guid and matched by substring.
    ///
    /// Then purges every legacy row. A comparison with no owner, or with neither identity,
    /// can never be attributed to a turn, and inventing an attribution would delete on a
    /// guess the first time somebody used /forget. Shadow data is diagnostic rather than
    /// authoritative: the telemetry can be regenerated by observing again, and the verbatim
    /// conversation it quotes cannot be un-kept.
    ///
    /// Idempotent -- a database already clean matches nothing. NOT reversible: Down()
    /// restores the column and not the rows, which is the point.
    /// </summary>
    public partial class AddShadowComparisonMemoryLineage : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "SourceMemoryId",
                table: "ShadowComparisons",
                type: "TEXT",
                nullable: true);

            migrationBuilder.Sql(
                """
                DELETE FROM ShadowComparisons
                WHERE UserId IS NULL
                   OR (SourceMessageId IS NULL AND SourceMemoryId IS NULL);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "SourceMemoryId",
                table: "ShadowComparisons");
        }
    }
}
