<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Companion.Cli</RootNamespace>
    <AssemblyName>companion</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.18" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Companion.Core\Companion.Core.csproj" />
    <ProjectReference Include="..\Companion.Infrastructure\Companion.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
