using System.Text.Json;
using Companion.Core;
using Companion.Infrastructure.Cognition;
using Microsoft.Extensions.Logging.Abstractions;
using Xunit;

namespace Companion.Tests;

/// <summary>
/// Proves the hand-written byte-level BPE produces exactly the ids Hugging Face's own tokenizer
/// produces for the same model.
///
/// This is the test the NLI model is allowed to exist because of. A tokenizer that is subtly wrong
/// throws nothing and returns plausible ids; the model then answers confidently about which of the
/// user's memories contradict each other, and supersession acts on it. Wrong in the shape of
/// working, on the one path that retires things the user told us.
///
/// The fixture was generated by `AutoTokenizer.from_pretrained("cross-encoder/nli-MiniLM2-L6-H768")`
/// and includes contractions, punctuation, symbols and an em dash — the places a byte-level
/// tokenizer goes wrong. Regenerate it if the model changes; never relax it to make a change pass.
/// </summary>
public class RobertaTokenizationTests
{
    private sealed record Reference(string A, string B, long[] Ids);

    private static string FixturePath =>
        Path.Combine(AppContext.BaseDirectory, "Fixtures", "data", "roberta-nli-tokenization.json");

    private static string? TokenizerPath()
    {
        // Only runs where the model has actually been fetched (tools/get-models.ps1). The weights
        // are gitignored, so this must skip rather than fail on a clean checkout or in CI.
        var candidates = new[]
        {
            Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..",
                "src", "Companion.Api", "models", "nli-tokenizer.json"),
        };
        return candidates.Select(Path.GetFullPath).FirstOrDefault(File.Exists);
    }

    [Fact]
    public void MatchesHuggingFaceTokenIdsExactly()
    {
        var tokenizerPath = TokenizerPath();
        if (tokenizerPath is null || !File.Exists(FixturePath))
            return; // model not fetched on this machine — nothing to verify against

        var tokenizer = RobertaLikeTokenizer.Load(
            new CognitiveModelEntry { Enabled = true, VocabPath = tokenizerPath },
            Path.GetDirectoryName(tokenizerPath)!,
            NullLogger.Instance);

        Assert.True(tokenizer.IsAvailable, tokenizer.Reason);

        var references = JsonSerializer.Deserialize<List<Reference>>(
            File.ReadAllText(FixturePath),
            new JsonSerializerOptions(JsonSerializerDefaults.Web))!;

        Assert.NotEmpty(references);
        foreach (var reference in references)
        {
            var encoded = tokenizer.EncodePair(reference.A, reference.B, maxTokens: 256);
            Assert.Equal(reference.Ids, encoded.InputIds);
            // RoBERTa has no segment embeddings; sending some would be a different model's input.
            Assert.Empty(encoded.TokenTypeIds);
            Assert.Equal(encoded.InputIds.Length, encoded.AttentionMask.Length);
        }
    }

    /// <summary>
    /// The byte encoder is the part with no room for interpretation: a leading space must become
    /// "Ġ", or every merge in the table misses and the ids are quietly wrong.
    /// </summary>
    [Theory]
    [InlineData(" the", "Ġthe")]
    [InlineData("the", "the")]
    [InlineData("\n", "Ċ")]
    public void ByteEncoderMatchesGpt2(string input, string expected)
        => Assert.Equal(expected, ByteLevel.Encode(input));
}
