using System.Security.Cryptography;
using System.Text;
using Xunit;

namespace Companion.PlanV3;

/// <summary>
/// The proof obligation for moving <c>admit_unknown</c> out of NEVER into its own ADMIT section:
/// every plan that does NOT carry an admit_unknown item must serialize to exactly the bytes it
/// serialized to before.
///
/// A section change is the kind of edit that can quietly reorder or re-wrap output for plans it
/// was never meant to touch, and the 804-plan manifest only says "something drifted". These tests
/// say which plans drifted and whether each one was entitled to.
///
/// The committed manifest is the BEFORE state - it was generated by the old serializer and is not
/// regenerated by these tests. That is what makes it usable as evidence rather than as a mirror.
/// </summary>
public class AdmitSectionProofTests
{
    private static string Sha256(string text)
        => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(text))).ToLowerInvariant();

    private static Dictionary<string, string> CommittedManifest()
    {
        var manifest = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var line in File.ReadAllLines(CompactV3GoldenTests.ManifestPath))
        {
            var trimmed = line.Trim();
            if (trimmed.Length == 0 || trimmed.StartsWith('#'))
                continue;
            var parts = trimmed.Split(' ', 2);
            if (parts.Length == 2)
                manifest[parts[0]] = parts[1].Trim();
        }
        return manifest;
    }

    /// <summary>Every corpus plan, with whether it carries an admitted unknown.</summary>
    private static IEnumerable<(string Id, PlanV3 Plan, bool HasAdmit)> Plans()
    {
        foreach (var (id, plan, _) in CorpusGoldenTests.CorpusPlans())
        {
            var v3 = V2Translation.FromV2(plan);
            if (PlanV3Codec.Validate(v3).Count > 0)
                continue;
            if (!PlanV3Codec.CheckRenderEligibility(v3).Eligible)
                continue;
            yield return (id, v3,
                v3.Items.Any(i => i.Policy == ExpressionPolicy.admit_unknown));
        }
    }

    [Fact]
    public void EveryPlanWithoutAnAdmittedUnknownIsByteIdentical()
    {
        var committed = CommittedManifest();
        var drifted = new List<string>();

        foreach (var (id, plan, hasAdmit) in Plans())
        {
            if (hasAdmit || !committed.TryGetValue(id, out var before))
                continue;
            if (Sha256(PlanV3Codec.CompactV3(plan)) != before)
                drifted.Add(id);
        }

        Assert.True(drifted.Count == 0,
            $"{drifted.Count} plan(s) with no admitted unknown changed bytes: "
            + string.Join(", ", drifted.Take(10)));
    }

    [Fact]
    public void EveryPlanThatDidChangeCarriesAnAdmittedUnknown()
    {
        var committed = CommittedManifest();
        var changed = new List<(string Id, bool HasAdmit)>();

        foreach (var (id, plan, hasAdmit) in Plans())
        {
            if (!committed.TryGetValue(id, out var before))
                continue;
            if (Sha256(PlanV3Codec.CompactV3(plan)) != before)
                changed.Add((id, hasAdmit));
        }

        // The change is expected to move SOMETHING - a proof that nothing changed would mean the
        // serializer edit did not take.
        Assert.NotEmpty(changed);
        Assert.All(changed, c => Assert.True(c.HasAdmit,
            $"{c.Id} changed bytes without carrying an admit_unknown item"));
    }

    [Fact]
    public void AnAdmittedUnknownRendersUnderAdmitAndNotUnderNever()
    {
        var plan = Plans().FirstOrDefault(p => p.HasAdmit).Plan;
        Assert.NotNull(plan);

        var rendered = PlanV3Codec.CompactV3(plan!);
        var admitted = plan!.Items.First(i => i.Policy == ExpressionPolicy.admit_unknown);

        Assert.Contains("ADMIT (say plainly that this is not known", rendered, StringComparison.Ordinal);

        // The item sits after the ADMIT header, and before NEVER if NEVER is present at all.
        var admitAt = rendered.IndexOf("ADMIT (", StringComparison.Ordinal);
        var itemAt = rendered.IndexOf(admitted.Text, StringComparison.Ordinal);
        Assert.True(itemAt > admitAt, "the admitted unknown does not sit under ADMIT");

        var neverAt = rendered.IndexOf("NEVER (", StringComparison.Ordinal);
        if (neverAt >= 0)
            Assert.True(itemAt < neverAt, "the admitted unknown is still under NEVER");
    }

    [Fact]
    public void NeverStillCarriesWhatMustNotBeExpressed()
    {
        // The other half of the correction: suppression must be exactly as strong as it was.
        // Splitting ADMIT out is only safe if must_not_express did not follow it.
        var plan = Plans()
            .Select(p => p.Plan)
            .FirstOrDefault(p => p.Items.Any(i => i.Policy == ExpressionPolicy.must_not_express));
        if (plan is null)
            return;                          // corpus has none; nothing to assert

        var rendered = PlanV3Codec.CompactV3(plan);
        var withheld = plan.Items.First(i => i.Policy == ExpressionPolicy.must_not_express);

        Assert.Contains("NEVER (do not assert, mention, or explain)", rendered, StringComparison.Ordinal);
        var neverAt = rendered.IndexOf("NEVER (", StringComparison.Ordinal);
        var itemAt = rendered.IndexOf(withheld.Text, StringComparison.Ordinal);
        Assert.True(itemAt > neverAt, "a must_not_express item left the NEVER section");
    }
}
